apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/yalzhang/investigation-lab?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main" && ( "coreos/***".pathChanged() || ".tekton/***".pathChanged() )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: fedora-coreos-kubevirt
    appstudio.openshift.io/component: fedora-coreos-kubevirt
    pipelines.appstudio.openshift.io/type: build
  name: fedora-coreos-kubevirt-on-pull-request
  namespace: cocl-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads-stage/cocl-tenant/fedora-coreos-kubevirt:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: coreos/Containerfile
  - name: path-context
    value: coreos
  pipelineSpec:
    description: |
      Custom pipeline for building fedora-coreos-kubevirt images using CoreOS Assembler (COSA).

      This pipeline builds a bootable Fedora CoreOS container with trustee components,
      converts it to a qcow2 disk image using COSA, and packages it as a container disk.
    params:
    - description: Source Repository URL
      name: git-url
      type: string
    - default: ""
      description: Revision of the Source Repository
      name: revision
      type: string
    - description: Fully Qualified Output Image
      name: output-image
      type: string
    - default: coreos
      description: Path to the source code of an application's component from where to build image.
      name: path-context
      type: string
    - default: coreos/Containerfile
      description: Path to the Dockerfile inside the context specified by parameter path-context
      name: dockerfile
      type: string
    - default: "false"
      description: Skip checks against built image
      name: skip-checks
      type: string
    - default: ""
      description: Image tag expiration time, time values could be something like 1h, 2d, 3w for hours, days, and weeks, respectively.
      name: image-expires-after
      type: string
    - default: "false"
      description: Enable cache proxy configuration
      name: enable-cache-proxy
      type: string
    results:
    - description: ""
      name: IMAGE_URL
      value: $(tasks.build-container.results.IMAGE_URL)
    - description: ""
      name: IMAGE_DIGEST
      value: $(tasks.build-container.results.IMAGE_DIGEST)
    - description: ""
      name: CHAINS-GIT_URL
      value: $(tasks.clone-repository.results.url)
    - description: ""
      name: CHAINS-GIT_COMMIT
      value: $(tasks.clone-repository.results.commit)
    tasks:
    - name: init
      params:
      - name: enable-cache-proxy
        value: $(params.enable-cache-proxy)
      taskRef:
        params:
        - name: name
          value: init
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-init:0.3@sha256:aa6f8632cc23d605c5942505ff1d00280db16a6fda5c4c56c4ed9ae936b5fbc6
        - name: kind
          value: task
        resolver: bundles
    - name: clone-repository
      params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: $(params.revision)
      runAfter:
      - init
      taskRef:
        params:
        - name: name
          value: git-clone
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-git-clone:0.1@sha256:865cdbe6094ff52d9e5dfc40d44ca5cfa6cee4b665aef91306356652fb84d7cc
        - name: kind
          value: task
        resolver: bundles
      workspaces:
      - name: output
        workspace: workspace
      - name: basic-auth
        workspace: git-auth

    # Step 1: Build the base bootable container image with trustee components
    - name: build-base-container
      params:
      - name: IMAGE
        value: $(params.output-image)-base
      - name: DOCKERFILE
        value: $(params.dockerfile)
      - name: CONTEXT
        value: $(params.path-context)
      - name: IMAGE_EXPIRES_AFTER
        value: $(params.image-expires-after)
      - name: BUILD_ARGS
        value:
        - BASE=quay.io/trusted-execution-clusters/fedora-coreos@sha256:6997f51fd27d1be1b5fc2e6cc3ebf16c17eb94d819b5d44ea8d6cf5f826ee773
        - COM_COREOS_OSNAME=fedora-coreos
      - name: BUILD_ARGS_FILE
        value: ""
      - name: HERMETIC
        value: "false"
      - name: PREFETCH_INPUT
        value: ""
      - name: COMMIT_SHA
        value: $(tasks.clone-repository.results.commit)
      - name: PRIVILEGED_NESTED
        value: "false"
      - name: SOURCE_URL
        value: $(tasks.clone-repository.results.url)
      - name: BUILDAH_FORMAT
        value: docker
      - name: HTTP_PROXY
        value: $(tasks.init.results.http-proxy)
      - name: NO_PROXY
        value: $(tasks.init.results.no-proxy)
      runAfter:
      - clone-repository
      taskRef:
        params:
        - name: name
          value: buildah
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-buildah:0.8@sha256:8b004faed787981488e3e72c88f063eb5ab2e2565c8b590e2e02348999a91d97
        - name: kind
          value: task
        resolver: bundles
      workspaces:
      - name: source
        workspace: workspace

    # Step 2: Export base container to OCI archive with proper credentials
    - name: export-oci-archive
      params:
      - name: image
        value: $(tasks.build-base-container.results.IMAGE_URL)
      runAfter:
      - build-base-container
      taskSpec:
        params:
        - name: image
          type: string
        steps:
        - name: export
          image: quay.io/skopeo/stable:latest
          script: |
            #!/bin/bash
            set -ex

            # Use registry credentials from the mounted docker config
            # The config.json contains auth for the registry
            export REGISTRY_AUTH_FILE=/credentials/.dockerconfigjson

            echo "Exporting image: $(params.image)"
            skopeo copy docker://$(params.image) oci-archive:/workspace/source/fcos.ociarchive

            echo "OCI archive created:"
            ls -lh /workspace/source/fcos.ociarchive
          volumeMounts:
          - name: registry-auth
            mountPath: /credentials
            readOnly: true
        volumes:
        - name: registry-auth
          secret:
            secretName: fedora-coreos-kubevirt-image-pull
        workspaces:
        - name: source
      workspaces:
      - name: source
        workspace: workspace

    # Steps 3 & 4: Initialize COSA and build KubeVirt qcow2 disk image
    - name: build-kubevirt-disk
      runAfter:
      - export-oci-archive
      taskSpec:
        steps:
        - name: cosa-init
          image: quay.io/coreos-assembler/coreos-assembler:latest
          securityContext:
            privileged: true
          script: |
            #!/bin/bash
            set -ex

            mkdir -p /workspace/source/cache
            cd /workspace/source/cache

            # Initialize COSA
            cosa init --force https://github.com/coreos/fedora-coreos-config

            # Import the OCI archive
            cosa import oci-archive:/workspace/source/fcos.ociarchive
          volumeMounts:
          - name: kvm
            mountPath: /dev/kvm
          - name: fuse
            mountPath: /dev/fuse
          workingDir: /workspace/source

        - name: cosa-build
          image: quay.io/coreos-assembler/coreos-assembler:latest
          securityContext:
            privileged: true
          script: |
            #!/bin/bash
            set -ex

            cd /workspace/source/cache

            # Build KubeVirt image
            cosa osbuild kubevirt

            # Find the generated qcow2 file
            QCOW2_FILE=$(find builds/latest -name "*.qcow2" | head -n1)

            if [ -z "$QCOW2_FILE" ]; then
              echo "Error: No qcow2 file found"
              exit 1
            fi

            # Copy to a known location
            mkdir -p /workspace/source/output
            cp "$QCOW2_FILE" /workspace/source/output/disk.qcow2

            echo "Disk image created at /workspace/source/output/disk.qcow2"
            ls -lh /workspace/source/output/disk.qcow2
          volumeMounts:
          - name: kvm
            mountPath: /dev/kvm
          - name: fuse
            mountPath: /dev/fuse
          workingDir: /workspace/source

        volumes:
        - name: kvm
          hostPath:
            path: /dev/kvm
            type: CharDevice
        - name: fuse
          hostPath:
            path: /dev/fuse
            type: CharDevice
        workspaces:
        - name: source
      workspaces:
      - name: source
        workspace: workspace

    # Step 5: Package qcow2 as container disk
    - name: build-container
      params:
      - name: IMAGE
        value: $(params.output-image)
      - name: DOCKERFILE
        value: coreos/Containerfile.cd
      - name: CONTEXT
        value: .
      - name: IMAGE_EXPIRES_AFTER
        value: $(params.image-expires-after)
      - name: BUILD_ARGS
        value:
        - IMAGE=output/disk.qcow2
      - name: BUILD_ARGS_FILE
        value: ""
      - name: HERMETIC
        value: "false"
      - name: PREFETCH_INPUT
        value: ""
      - name: COMMIT_SHA
        value: $(tasks.clone-repository.results.commit)
      - name: PRIVILEGED_NESTED
        value: "false"
      - name: SOURCE_URL
        value: $(tasks.clone-repository.results.url)
      - name: BUILDAH_FORMAT
        value: docker
      - name: HTTP_PROXY
        value: $(tasks.init.results.http-proxy)
      - name: NO_PROXY
        value: $(tasks.init.results.no-proxy)
      runAfter:
      - build-kubevirt-disk
      taskRef:
        params:
        - name: name
          value: buildah
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-buildah:0.8@sha256:8b004faed787981488e3e72c88f063eb5ab2e2565c8b590e2e02348999a91d97
        - name: kind
          value: task
        resolver: bundles
      workspaces:
      - name: source
        workspace: workspace

    # Security and validation checks on final image
    - name: deprecated-base-image-check
      params:
      - name: IMAGE_URL
        value: $(tasks.build-container.results.IMAGE_URL)
      - name: IMAGE_DIGEST
        value: $(tasks.build-container.results.IMAGE_DIGEST)
      runAfter:
      - build-container
      taskRef:
        params:
        - name: name
          value: deprecated-image-check
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-deprecated-image-check:0.5@sha256:808fe09bb5b8503de569de097ae5dd619a7488110f79e8e215e69862ee3fce6d
        - name: kind
          value: task
        resolver: bundles
      when:
      - input: $(params.skip-checks)
        operator: in
        values:
        - "false"

    - name: clair-scan
      params:
      - name: image-digest
        value: $(tasks.build-container.results.IMAGE_DIGEST)
      - name: image-url
        value: $(tasks.build-container.results.IMAGE_URL)
      runAfter:
      - build-container
      taskRef:
        params:
        - name: name
          value: clair-scan
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-clair-scan:0.3@sha256:654b989d7cdc03d082e56f216a29de04847215ee379a8d9ca315e453ad2b15c2
        - name: kind
          value: task
        resolver: bundles
      when:
      - input: $(params.skip-checks)
        operator: in
        values:
        - "false"

    - name: clamav-scan
      params:
      - name: image-digest
        value: $(tasks.build-container.results.IMAGE_DIGEST)
      - name: image-url
        value: $(tasks.build-container.results.IMAGE_URL)
      runAfter:
      - build-container
      taskRef:
        params:
        - name: name
          value: clamav-scan
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-clamav-scan:0.3@sha256:b2f25599a10ab0846e4659f76b5b78c0fddf561404656fda52055eda31e70d83
        - name: kind
          value: task
        resolver: bundles
      when:
      - input: $(params.skip-checks)
        operator: in
        values:
        - "false"

    workspaces:
    - name: workspace
    - name: git-auth
      optional: true
  taskRunTemplate:
    serviceAccountName: build-pipeline-fedora-coreos-kubevirt
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
