---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/yalzhang/investigation-lab?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main" && ( "coreos/***".pathChanged() || ".tekton/***".pathChanged() )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: fedora-coreos-kubevirt
    appstudio.openshift.io/component: fedora-coreos-kubevirt
    pipelines.appstudio.openshift.io/type: build
  name: fedora-coreos-kubevirt-on-pull-request
  namespace: cocl-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads-stage/cocl-tenant/fedora-coreos-kubevirt:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: coreos/Containerfile
  - name: path-context
    value: coreos
  - name: skip-checks
    value: "false"
  pipelineSpec:
    finally:
    - name: show-sbom
      params:
      - name: IMAGE_URL
        value: $(tasks.build-container.results.IMAGE_URL)
      taskRef:
        params:
        - name: name
          value: show-sbom
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-show-sbom:0.1@sha256:9bfc6b99ef038800fe131d7b45ff3cd4da3a415dd536f7c657b3527b01c4a13b
        - name: kind
          value: task
        resolver: bundles
    - name: show-summary
      params:
      - name: pipelinerun-name
        value: $(context.pipelineRun.name)
      - name: git-url
        value: $(tasks.clone-repository.results.url)?rev=$(tasks.clone-repository.results.commit)
      - name: image-url
        value: $(params.output-image)
      taskRef:
        params:
        - name: name
          value: summary
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-summary:0.2@sha256:d97c04ab42f277b1103eb6f3a053b247849f4f5b3237ea302a8ecada3b24e15b
        - name: kind
          value: task
        resolver: bundles
      workspaces:
      - name: workspace
        workspace: workspace
    params:
    - description: Source Repository URL
      name: git-url
      type: string
    - default: ""
      description: Revision of the Source Repository
      name: revision
      type: string
    - description: Fully Qualified Output Image
      name: output-image
      type: string
    - default: coreos
      description: Path to the source code of an application's component from where to build image.
      name: path-context
      type: string
    - default: coreos/Containerfile
      description: Path to the Dockerfile inside the context specified by parameter path-context
      name: dockerfile
      type: string
    - default: ""
      description: Image tag expiration time, time values could be something like 1h, 2d, 3w for hours, days, and weeks, respectively.
      name: image-expires-after
      type: string
    - default: "false"
      description: Skip checks against built image
      name: skip-checks
      type: string
    results:
    - description: ""
      name: IMAGE_URL
      value: $(tasks.build-container.results.IMAGE_URL)
    - description: ""
      name: IMAGE_DIGEST
      value: $(tasks.build-container.results.IMAGE_DIGEST)
    - description: ""
      name: CHAINS-GIT_URL
      value: $(tasks.clone-repository.results.url)
    - description: ""
      name: CHAINS-GIT_COMMIT
      value: $(tasks.clone-repository.results.commit)
    tasks:
    - name: init
      params:
      - name: image-url
        value: $(params.output-image)
      - name: rebuild
        value: "true"
      - name: skip-checks
        value: $(params.skip-checks)
      taskRef:
        params:
        - name: name
          value: init
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-init:0.2@sha256:ebf06778aeacbbeb081f9231eafbdfdb8e380ad04e211d7ed80ae9101e37fd82
        - name: kind
          value: task
        resolver: bundles
    - name: clone-repository
      params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: $(params.revision)
      runAfter:
      - init
      taskRef:
        params:
        - name: name
          value: git-clone
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-git-clone:0.1@sha256:306b69e6db435ad4a7cf258b6219d9b998eb37da44f5e9ac882ac86a08109154
        - name: kind
          value: task
        resolver: bundles
      when:
      - input: $(tasks.init.results.build)
        operator: in
        values:
        - "true"
      workspaces:
      - name: output
        workspace: workspace
      - name: basic-auth
        workspace: git-auth

    # Build the base bootable container image
    - name: build-base-container
      params:
      - name: IMAGE
        value: $(params.output-image)-base
      - name: DOCKERFILE
        value: $(params.dockerfile)
      - name: CONTEXT
        value: $(params.path-context)
      - name: IMAGE_EXPIRES_AFTER
        value: $(params.image-expires-after)
      - name: BUILD_ARGS
        value:
        - BASE=quay.io/trusted-execution-clusters/fedora-coreos@sha256:6997f51fd27d1be1b5fc2e6cc3ebf16c17eb94d819b5d44ea8d6cf5f826ee773
        - COM_COREOS_OSNAME=fedora-coreos
      - name: BUILD_ARGS_FILE
        value: ""
      runAfter:
      - clone-repository
      taskRef:
        params:
        - name: name
          value: buildah
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-buildah:0.2@sha256:ba9564699ca5dc84abb1307bda07ecf42058e4a153b3f1d4fd0d2e511d42a44d
        - name: kind
          value: task
        resolver: bundles
      when:
      - input: $(tasks.init.results.build)
        operator: in
        values:
        - "true"
      workspaces:
      - name: source
        workspace: workspace

    # Export base container to OCI archive
    - name: export-oci-archive
      params:
      - name: image
        value: $(tasks.build-base-container.results.IMAGE_URL)
      - name: format
        value: oci
      runAfter:
      - build-base-container
      taskSpec:
        params:
        - name: image
          type: string
        - name: format
          type: string
        steps:
        - name: export
          image: quay.io/skopeo/stable:latest
          script: |
            #!/bin/bash
            set -e
            skopeo copy docker://$(params.image) oci-archive:/workspace/source/fcos.ociarchive
        workspaces:
        - name: source
      workspaces:
      - name: source
        workspace: workspace

    # Run CoreOS Assembler to build KubeVirt disk image
    - name: build-kubevirt-disk
      runAfter:
      - export-oci-archive
      taskSpec:
        steps:
        - name: cosa-init
          image: quay.io/coreos-assembler/coreos-assembler:latest
          securityContext:
            privileged: true
          script: |
            #!/bin/bash
            set -ex

            mkdir -p /workspace/source/cache
            cd /workspace/source/cache

            # Initialize COSA
            cosa init --force https://github.com/coreos/fedora-coreos-config

            # Import the OCI archive
            cosa import oci-archive:/workspace/source/fcos.ociarchive
          volumeMounts:
          - name: kvm
            mountPath: /dev/kvm
          - name: fuse
            mountPath: /dev/fuse
          workingDir: /workspace/source

        - name: cosa-build
          image: quay.io/coreos-assembler/coreos-assembler:latest
          securityContext:
            privileged: true
          script: |
            #!/bin/bash
            set -ex

            cd /workspace/source/cache

            # Build KubeVirt image
            cosa osbuild kubevirt

            # Find the generated qcow2 file
            QCOW2_FILE=$(find builds/latest -name "*.qcow2" | head -n1)

            if [ -z "$QCOW2_FILE" ]; then
              echo "Error: No qcow2 file found"
              exit 1
            fi

            # Copy to a known location
            mkdir -p /workspace/source/output
            cp "$QCOW2_FILE" /workspace/source/output/disk.qcow2

            echo "Disk image created at /workspace/source/output/disk.qcow2"
            ls -lh /workspace/source/output/disk.qcow2
          volumeMounts:
          - name: kvm
            mountPath: /dev/kvm
          - name: fuse
            mountPath: /dev/fuse
          workingDir: /workspace/source

        volumes:
        - name: kvm
          hostPath:
            path: /dev/kvm
            type: CharDevice
        - name: fuse
          hostPath:
            path: /dev/fuse
            type: CharDevice
        workspaces:
        - name: source
      workspaces:
      - name: source
        workspace: workspace

    # Build final container with disk image
    - name: build-container
      params:
      - name: IMAGE
        value: $(params.output-image)
      - name: DOCKERFILE
        value: coreos/Containerfile.cd
      - name: CONTEXT
        value: .
      - name: IMAGE_EXPIRES_AFTER
        value: $(params.image-expires-after)
      - name: BUILD_ARGS
        value:
        - IMAGE=output/disk.qcow2
      runAfter:
      - build-kubevirt-disk
      taskRef:
        params:
        - name: name
          value: buildah
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-buildah:0.2@sha256:ba9564699ca5dc84abb1307bda07ecf42058e4a153b3f1d4fd0d2e511d42a44d
        - name: kind
          value: task
        resolver: bundles
      when:
      - input: $(tasks.init.results.build)
        operator: in
        values:
        - "true"
      workspaces:
      - name: source
        workspace: workspace

    # Security and validation checks on final image
    - name: deprecated-base-image-check
      params:
      - name: IMAGE_URL
        value: $(tasks.build-container.results.IMAGE_URL)
      - name: IMAGE_DIGEST
        value: $(tasks.build-container.results.IMAGE_DIGEST)
      runAfter:
      - build-container
      taskRef:
        params:
        - name: name
          value: deprecated-image-check
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-deprecated-image-check:0.5@sha256:808fe09bb5b8503de569de097ae5dd619a7488110f79e8e215e69862ee3fce6d
        - name: kind
          value: task
        resolver: bundles
      when:
      - input: $(params.skip-checks)
        operator: in
        values:
        - "false"

    - name: clair-scan
      params:
      - name: image-digest
        value: $(tasks.build-container.results.IMAGE_DIGEST)
      - name: image-url
        value: $(tasks.build-container.results.IMAGE_URL)
      runAfter:
      - build-container
      taskRef:
        params:
        - name: name
          value: clair-scan
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-clair-scan:0.3@sha256:654b989d7cdc03d082e56f216a29de04847215ee379a8d9ca315e453ad2b15c2
        - name: kind
          value: task
        resolver: bundles
      when:
      - input: $(params.skip-checks)
        operator: in
        values:
        - "false"

    - name: clamav-scan
      params:
      - name: image-digest
        value: $(tasks.build-container.results.IMAGE_DIGEST)
      - name: image-url
        value: $(tasks.build-container.results.IMAGE_URL)
      runAfter:
      - build-container
      taskRef:
        params:
        - name: name
          value: clamav-scan
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-clamav-scan:0.3@sha256:b2f25599a10ab0846e4659f76b5b78c0fddf561404656fda52055eda31e70d83
        - name: kind
          value: task
        resolver: bundles
      when:
      - input: $(params.skip-checks)
        operator: in
        values:
        - "false"

    workspaces:
    - name: workspace
    - name: git-auth
      optional: true
  taskRunTemplate:
    serviceAccountName: build-pipeline-fedora-coreos-kubevirt
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
